version: "1.0.0"
env: "local" 
storage: 
  user: yerdaulet 
  password: pa55word 
  host: localhost 
  port: "5432"
  dbname: prosclad 
  sslmode: disable 
  pool_max_conns: 10
  pool_min_conns: 2
  pool_max_conn_idle_time: "15m"
logfile: "./log/log.txt"
http: 
  address: "8080"
  timeout: 5s
  idle: 15s
ratelimiter:
  maxreq: 20
  exp: 5s